name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
        include:
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: [4, 8]

      #fail-fast: true # if false, then all jobs will run even if fail on one of the node versions
      #max-parallel: 2  #  specify number of parallel jobs
    runs-on: ${{matrix.os}} #reference matrix.os
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps: 
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:  
          node-version: ${{ matrix.node_version }} #reference matrix.node_version
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_8