name: Write a File to Repo

on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Write file to pwd
        run: echo $RANDOM > random.txt
      - name: List Files After Checkout
        run: |
          pwd
          ls -a