name: Write a File to Repo

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: List files before Checkout
        run: |
          pwd
          ls -a
      - name: Checkout
      - uses: actions/checkout@v1
      - name: List files After Checkout
        run: |
          pwd
          ls -a